Correct float pretty-printing
MLton's Real64.toString prints doubles that have no fractional part the
same as integers. This doesn't play well with C, since C won't convert
integers to doubles unless it absolutely has to; for example, it will
evaluate 3/5 to 0 instead of 0.6. To avoid this, always print doubles in
scientific notation, which forces the C parser to parse them as doubles.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -148,4 +148,9 @@ test:
 	else \
 		echo "Skipped IPv6 tests."; \
 	fi
+	bin/urweb -boot -noEmacs tests/float2
+	tests/float2.exe -q -a 127.0.0.1 & echo $$! >$(TESTPID)
+	sleep 1
+	(curl -s 'http://localhost:8080/main' | grep -Fq 0.6) || (kill `cat $(TESTPID)`; echo "Test 'float2' failed"; /bin/false)
+	kill `cat $(TESTPID)`
 	echo Tests succeeded.
